
import java.awt.Dimension;
import java.awt.Toolkit;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JComboBox;
import javax.swing.JTextField;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Adam Wisnu Pradana
 * @author Muhammad Wildan Hafizh
 * @author Rr. Nurrizka Puspa Wiranti
 * @author Eldorado Valentino Sitompul
 */

//interface
interface HargaTiketCalculator {
    int hitungTotalHarga();
}

class HitungHargaTiket implements HargaTiketCalculator {
    public int harga;
    public int jumlahTiket;
    
    public HitungHargaTiket(int harga, int jumlahTiket){
        this.harga = harga;
        this.jumlahTiket = jumlahTiket;
    }
    
     // Overload 
    public int hitungTotalHarga(String promo) {
        int totalHarga = harga * jumlahTiket; 
        
        if ("Promo".equalsIgnoreCase(promo)) {
            double diskon = 0.1;
            totalHarga = (int) (totalHarga - (totalHarga * diskon));
        } 
        return totalHarga;
    }
//    override
    @Override
    public int hitungTotalHarga() {
        return harga * jumlahTiket;
    }
}

public class PembelianTiket extends javax.swing.JFrame {

    static String pemesan;
    static String maskapai;
    static String berangkat;
    static String tujuan;
    static String kelas;
    static String harga;
    static String tiketDibeli;
    static String totalHargaTiketDibeli;
    int hargaTiket = 0, jumlahTiket, totalHarga = 0;
    boolean pembelianBerhasil = false;
   
    
    /**
     * Creates new form PembelianTiket
     */
    public PembelianTiket() {
        initComponents();
        
        Dimension layar = Toolkit.getDefaultToolkit().getScreenSize();
        int x = layar.width / 2 - this.getSize().width / 2;
        int y = layar.height / 2 - this.getSize().height / 2;
        this.setLocation(x, y);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        lblJudul = new javax.swing.JLabel();
        lblNama = new javax.swing.JLabel();
        lblMaskapai = new javax.swing.JLabel();
        lblTujuan = new javax.swing.JLabel();
        lblTipe = new javax.swing.JLabel();
        lblHargaTiket = new javax.swing.JLabel();
        lblJumlahTiket = new javax.swing.JLabel();
        lblTotalHarga = new javax.swing.JLabel();
        formNama = new javax.swing.JTextField();
        cbMaskapai = new javax.swing.JComboBox<>();
        cbTujuan = new javax.swing.JComboBox<>();
        rbEkonomi = new javax.swing.JRadioButton();
        rbBisnis = new javax.swing.JRadioButton();
        rbEksekutif = new javax.swing.JRadioButton();
        formHargaTiket = new javax.swing.JTextField();
        formJumlahTiket = new javax.swing.JTextField();
        formTotalHarga = new javax.swing.JTextField();
        btnPesanLagi = new javax.swing.JButton();
        btnPesan = new javax.swing.JButton();
        btnSelesai = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        btnHitung = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(102, 204, 0));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        lblJudul.setBackground(new java.awt.Color(102, 153, 255));
        lblJudul.setFont(new java.awt.Font("JetBrains Mono SemiBold", 0, 36)); // NOI18N
        lblJudul.setForeground(new java.awt.Color(255, 0, 102));
        lblJudul.setText("TIKET PESAWAT BANDUNG");
        lblJudul.setAutoscrolls(true);

        lblNama.setText("Nama");

        lblMaskapai.setText("Maskapai");

        lblTujuan.setText("Tujuan");

        lblTipe.setText("Tipe");

        lblHargaTiket.setText("Harga Tiket");

        lblJumlahTiket.setText("Jumlah Tiket");

        lblTotalHarga.setText("Total Harga");

        formNama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                formNamaActionPerformed(evt);
            }
        });

        cbMaskapai.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        cbMaskapai.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "GARUDA", "CITILINK", "AIRASIA", " " }));
        cbMaskapai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbMaskapaiActionPerformed(evt);
            }
        });

        cbTujuan.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        cbTujuan.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "JUANDA", "MINANG", "SOETA" }));
        cbTujuan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbTujuanActionPerformed(evt);
            }
        });

        buttonGroup1.add(rbEkonomi);
        rbEkonomi.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        rbEkonomi.setText("Ekonomi");
        rbEkonomi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbEkonomiActionPerformed(evt);
            }
        });

        buttonGroup1.add(rbBisnis);
        rbBisnis.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        rbBisnis.setText("Bisnis");
        rbBisnis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbBisnisActionPerformed(evt);
            }
        });

        buttonGroup1.add(rbEksekutif);
        rbEksekutif.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        rbEksekutif.setText("Eksekutif");
        rbEksekutif.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbEksekutifActionPerformed(evt);
            }
        });

        formHargaTiket.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                formHargaTiketActionPerformed(evt);
            }
        });

        formJumlahTiket.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                formJumlahTiketActionPerformed(evt);
            }
        });

        formTotalHarga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                formTotalHargaActionPerformed(evt);
            }
        });

        btnPesanLagi.setBackground(new java.awt.Color(255, 0, 102));
        btnPesanLagi.setFont(new java.awt.Font("JetBrains Mono ExtraBold", 0, 12)); // NOI18N
        btnPesanLagi.setForeground(new java.awt.Color(255, 255, 255));
        btnPesanLagi.setText("PESAN LAGI");
        btnPesanLagi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPesanLagiActionPerformed(evt);
            }
        });

        btnPesan.setBackground(new java.awt.Color(255, 0, 102));
        btnPesan.setFont(new java.awt.Font("JetBrains Mono ExtraBold", 0, 12)); // NOI18N
        btnPesan.setForeground(new java.awt.Color(255, 255, 255));
        btnPesan.setText("CETAK RESI");
        btnPesan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPesanActionPerformed(evt);
            }
        });

        btnSelesai.setBackground(new java.awt.Color(255, 0, 102));
        btnSelesai.setFont(new java.awt.Font("JetBrains Mono ExtraBold", 0, 12)); // NOI18N
        btnSelesai.setForeground(new java.awt.Color(255, 255, 255));
        btnSelesai.setText("SELESAI");
        btnSelesai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSelesaiActionPerformed(evt);
            }
        });

        jLabel1.setText("Berangkat dari Bandara Internasional Husein Sastranegara ");

        btnHitung.setBackground(new java.awt.Color(255, 0, 102));
        btnHitung.setFont(new java.awt.Font("JetBrains Mono ExtraBold", 0, 12)); // NOI18N
        btnHitung.setForeground(new java.awt.Color(255, 255, 255));
        btnHitung.setText("HITUNG DONG!");
        btnHitung.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHitungActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(139, 139, 139))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblMaskapai)
                                .addGap(37, 37, 37)
                                .addComponent(cbMaskapai, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblHargaTiket)
                                .addGap(29, 29, 29)
                                .addComponent(formHargaTiket))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblJumlahTiket)
                                    .addComponent(lblTotalHarga))
                                .addGap(24, 24, 24)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(15, 15, 15)
                                        .addComponent(btnPesanLagi)
                                        .addGap(18, 18, 18)
                                        .addComponent(btnPesan)
                                        .addGap(116, 116, 116))
                                    .addComponent(formJumlahTiket)
                                    .addComponent(formTotalHarga)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblTipe)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(87, 87, 87)
                                        .addComponent(rbEkonomi)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(rbBisnis)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(rbEksekutif))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblTujuan)
                                .addGap(52, 52, 52)
                                .addComponent(cbTujuan, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblNama)
                                .addGap(56, 56, 56)
                                .addComponent(formNama, javax.swing.GroupLayout.PREFERRED_SIZE, 308, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnHitung))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(185, 185, 185)
                        .addComponent(btnSelesai))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(64, 64, 64)
                        .addComponent(lblJudul)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblJudul)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNama)
                    .addComponent(formNama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbMaskapai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblMaskapai))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbTujuan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblTujuan))
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTipe)
                    .addComponent(rbEkonomi)
                    .addComponent(rbBisnis)
                    .addComponent(rbEksekutif))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblHargaTiket)
                    .addComponent(formHargaTiket, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblJumlahTiket)
                    .addComponent(formJumlahTiket, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnHitung))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTotalHarga)
                    .addComponent(formTotalHarga, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnPesanLagi)
                    .addComponent(btnPesan))
                .addGap(18, 18, 18)
                .addComponent(btnSelesai)
                .addContainerGap(82, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formJumlahTiketActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_formJumlahTiketActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_formJumlahTiketActionPerformed

    private void formHargaTiketActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_formHargaTiketActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_formHargaTiketActionPerformed

    // Inheritance
    public class HitungHargaEksekutif extends HitungHargaTiket implements HargaTiketCalculator {

    private final JComboBox<String> cbMaskapai;
    private final JComboBox<String> cbTujuan;
    private final JTextField formHargaTiket;
    private final JTextField formJumlahTiket;

    public HitungHargaEksekutif(int harga, int jumlahTiket, JComboBox<String> cbMaskapai, JComboBox<String> cbTujuan, JTextField formHargaTiket, JTextField formJumlahTiket) {
        super(harga, jumlahTiket);
        this.cbMaskapai = cbMaskapai;
        this.cbTujuan = cbTujuan;
        this.formHargaTiket = formHargaTiket;
        this.formJumlahTiket = formJumlahTiket;
    }
    
    @Override
    public int hitungTotalHarga() {
        String[] maskapaiOptions = { "CITILINK", "AIRASIA", "GARUDA" };
        String[] tujuanOptions = { "MINANG", "SOETA", "JUANDA" };

        int[][] hargaTiketMatrix = {
                { 1900000, 1500000, 1700000 },
                { 2300000, 1900000, 2100000 },
                { 2500000, 2100000, 2300000 }
        };

        String selectedMaskapai = cbMaskapai.getSelectedItem().toString();
        String selectedTujuan = cbTujuan.getSelectedItem().toString();

        hargaTiket = 0;

         // COnditional and looping
        for (int i = 0; i < maskapaiOptions.length; i++) {
            if (selectedMaskapai.equals(maskapaiOptions[i])) {
                for (int j = 0; j < tujuanOptions.length; j++) {
                    if (selectedTujuan.equals(tujuanOptions[j])) {
                        hargaTiket = hargaTiketMatrix[i][j];
                        break;
                    }
                }
                break;
            }
        }

        formHargaTiket.setText(String.valueOf(hargaTiket));

        // Call the hitungTotalHarga method from HitungHargaTiket
        return super.hitungTotalHarga();
    }
}
    
    private void rbEksekutifActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbEksekutifActionPerformed
        // TODO add your handling code here:
    HitungHargaEksekutif hitungHargaEksekutif = new HitungHargaEksekutif(hargaTiket, jumlahTiket, cbMaskapai, cbTujuan, formHargaTiket, formJumlahTiket);
    int totalHargaEksekutif = hitungHargaEksekutif.hitungTotalHarga();
    }//GEN-LAST:event_rbEksekutifActionPerformed
    
    // Inheritance
    public class HitungHargaBisnis extends HitungHargaTiket implements HargaTiketCalculator {

        private final JComboBox<String> cbMaskapai;
        private final JComboBox<String> cbTujuan;
        private final JTextField formHargaTiket;
        private final JTextField formJumlahTiket;

    // Constructor for HitungHargaBisnis
    public HitungHargaBisnis(int harga, int jumlahTiket, JComboBox<String> cbMaskapai, JComboBox<String> cbTujuan, JTextField formHargaTiket, JTextField formJumlahTiket) {
        super(harga, jumlahTiket);
        this.cbMaskapai = cbMaskapai;
        this.cbTujuan = cbTujuan;
        this.formHargaTiket = formHargaTiket;
        this.formJumlahTiket = formJumlahTiket;
    }

    // Implement the hitungTotalHarga method from HargaTiketCalculator
    @Override
    public int hitungTotalHarga() {
        String[] maskapaiOptions = {"CITILINK", "AIRASIA", "GARUDA"};
        String[] tujuanOptions = {"MINANG", "SOETA", "JUANDA"};

        int[][] hargaTiketMatrix = {
            {1700000, 1300000, 1500000},
            {2100000, 1700000, 1900000},
            {2300000, 1900000, 2100000}
        };

        String selectedMaskapai = cbMaskapai.getSelectedItem().toString();
        String selectedTujuan = cbTujuan.getSelectedItem().toString();

        hargaTiket = 0;
        
        // COnditional and looping
        for (int i = 0; i < maskapaiOptions.length; i++) {
            if (selectedMaskapai.equals(maskapaiOptions[i])) {
                for (int j = 0; j < tujuanOptions.length; j++) {
                    if (selectedTujuan.equals(tujuanOptions[j])) {
                        hargaTiket = hargaTiketMatrix[i][j];
                        break;
                    }
                }
                break;
            }
        }

        formHargaTiket.setText(String.valueOf(hargaTiket));

        // Call the hitungTotalHarga method from HitungHargaTiket
        return super.hitungTotalHarga();
    }
    }
    
    private void rbBisnisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbBisnisActionPerformed
        // TODO add your handling code here:
    HitungHargaBisnis hitungHargaBisnis = new HitungHargaBisnis(hargaTiket, jumlahTiket, cbMaskapai, cbTujuan, formHargaTiket, formJumlahTiket);
    int totalHargaBisnis = hitungHargaBisnis.hitungTotalHarga();
    }//GEN-LAST:event_rbBisnisActionPerformed

// Inheritance    
public class HitungHargaEkonomi extends HitungHargaTiket implements HargaTiketCalculator {

    private final JComboBox<String> cbMaskapai;
    private final JComboBox<String> cbTujuan;
    private final JTextField formHargaTiket;
    private final JTextField formJumlahTiket;

    // Constructor for HitungHargaBisnis
    public HitungHargaEkonomi(int harga, int jumlahTiket, JComboBox<String> cbMaskapai, JComboBox<String> cbTujuan, JTextField formHargaTiket, JTextField formJumlahTiket) {
        super(harga, jumlahTiket);
        this.cbMaskapai = cbMaskapai;
        this.cbTujuan = cbTujuan;
        this.formHargaTiket = formHargaTiket;
        this.formJumlahTiket = formJumlahTiket;
    }

    // Implement the hitungTotalHarga method from HargaTiketCalculator
    @Override
    public int hitungTotalHarga() {
        String[] maskapaiOptions = {"CITILINK", "AIRASIA", "GARUDA"};
        String[] tujuanOptions = {"MINANG", "SOETA", "JUANDA"};

        int[][] hargaTiketMatrix = {
            {1500000, 1100000, 1300000},
            {1900000, 1500000, 1700000},
            {2100000, 1700000, 1900000}
        };

        String selectedMaskapai = cbMaskapai.getSelectedItem().toString();
        String selectedTujuan = cbTujuan.getSelectedItem().toString();

        hargaTiket = 0;

         // COnditional and looping
        for (int i = 0; i < maskapaiOptions.length; i++) {
            if (selectedMaskapai.equals(maskapaiOptions[i])) {
                for (int j = 0; j < tujuanOptions.length; j++) {
                    if (selectedTujuan.equals(tujuanOptions[j])) {
                        hargaTiket = hargaTiketMatrix[i][j];
                        break;
                    }
                }
                break;
            }
        }

        formHargaTiket.setText(String.valueOf(hargaTiket));

        // Call the hitungTotalHarga method from HitungHargaTiket
        return super.hitungTotalHarga();
    }

}
    
    private void rbEkonomiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbEkonomiActionPerformed
        // TODO add your handling code here:
    HitungHargaEkonomi hitungHargaEkonomi = new HitungHargaEkonomi(hargaTiket, jumlahTiket, cbMaskapai, cbTujuan, formHargaTiket, formJumlahTiket);
    int totalHargaEkonomi = hitungHargaEkonomi.hitungTotalHarga();
    }//GEN-LAST:event_rbEkonomiActionPerformed

    private void cbTujuanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbTujuanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbTujuanActionPerformed

    private void cbMaskapaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbMaskapaiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbMaskapaiActionPerformed

    private void formNamaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_formNamaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_formNamaActionPerformed

    private void formTotalHargaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_formTotalHargaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_formTotalHargaActionPerformed

    private void btnPesanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPesanActionPerformed
        // TODO add your handling code here:
    pembelianBerhasil = true;
    pemesan = formNama.getText();
    maskapai = (String) cbMaskapai.getSelectedItem(); // Ambil item terpilih dari JComboBox
    tujuan = (String) cbTujuan.getSelectedItem(); // Ambil item terpilih dari JComboBox
    berangkat = "Bandara Internasional Husein Sastranegara";

    // Periksa radio button yang terpilih untuk mendapatkan tipe
    kelas = "";
    if (rbEkonomi.isSelected()) {
        kelas = "Ekonomi";
    } else if (rbBisnis.isSelected()) {
        kelas = "Bisnis";
    } else if (rbEksekutif.isSelected()) {
        kelas = "Eksekutif";
    }

    harga = formHargaTiket.getText();
    tiketDibeli = formJumlahTiket.getText();
    totalHargaTiketDibeli = formTotalHarga.getText();
       
    // Kirim nilai ke ResiTiket menggunakan konstruktor
    ResiTiket resiTiket = new ResiTiket(pemesan, maskapai, tujuan, kelas, harga, tiketDibeli, totalHargaTiketDibeli);
    
    // Menampilkan GUI ResiTiket
    resiTiket.pack();
    resiTiket.setVisible(true);
    resiTiket.setLocationRelativeTo(null);

    // Mengatur operasi penutupan jendela pada objek ResiTiket
    resiTiket.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE); 

    // Menutup jendela saat ini
    this.dispose();
    }//GEN-LAST:event_btnPesanActionPerformed

    private void btnHitungActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHitungActionPerformed
        // TODO add your handling code here:
    jumlahTiket = Integer.parseInt(formJumlahTiket.getText());

    // Initialize totalHarga variable
    totalHarga = 0;

    // Check the selected option (Bisnis or Eksekutif)
    if (rbBisnis.isSelected()) {
        // Calculate totalHarga for Bisnis
        HitungHargaBisnis hitungHargaBisnis = new HitungHargaBisnis(hargaTiket, jumlahTiket, cbMaskapai, cbTujuan, formHargaTiket, formJumlahTiket);
        
        if (jumlahTiket >= 3) {
            String promoCode = "Promo";
            totalHarga = hitungHargaBisnis.hitungTotalHarga(promoCode);
            } else {
            totalHarga = hitungHargaBisnis.hitungTotalHarga();
            }
//        totalHarga = hitungHargaBisnis.hitungTotalHarga();
    } else if (rbEksekutif.isSelected()) {
        // Calculate totalHarga for Eksekutif
        HitungHargaEksekutif hitungHargaEksekutif = new HitungHargaEksekutif(hargaTiket, jumlahTiket, cbMaskapai, cbTujuan, formHargaTiket, formJumlahTiket);
        
        if (jumlahTiket >= 2) {
            String promoCode = "Promo";
            totalHarga = hitungHargaEksekutif.hitungTotalHarga(promoCode);
            } else {
            totalHarga = hitungHargaEksekutif.hitungTotalHarga();
            }
        
//        totalHarga = hitungHargaEksekutif.hitungTotalHarga();
    }else if (rbEkonomi.isSelected()) {
        // Calculate totalHarga for Eksekutif
        HitungHargaEkonomi hitungHargaEkonomi = new HitungHargaEkonomi(hargaTiket, jumlahTiket, cbMaskapai, cbTujuan, formHargaTiket, formJumlahTiket);
        if (jumlahTiket >= 4) {
            String promoCode = "Promo"; 
            totalHarga = hitungHargaEkonomi.hitungTotalHarga(promoCode);
            } else {
            totalHarga = hitungHargaEkonomi.hitungTotalHarga();
            }
//        totalHarga = hitungHargaEkonomi.hitungTotalHarga();
    }

    // Display the totalHarga
    formTotalHarga.setText(String.valueOf(totalHarga));
    }//GEN-LAST:event_btnHitungActionPerformed

    private void btnPesanLagiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPesanLagiActionPerformed
        // TODO add your handling code here:
        formNama.setText("");
        cbMaskapai.setSelectedItem("GARUDA");
        cbTujuan.setSelectedItem("JUANDA");
        formHargaTiket.setText("");
        formJumlahTiket.setText("");
        formTotalHarga.setText("");
        buttonGroup1.clearSelection();
    }//GEN-LAST:event_btnPesanLagiActionPerformed

    private void btnSelesaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSelesaiActionPerformed
        // TODO add your handling code here:
        int konfirmasi = JOptionPane.showConfirmDialog(null, "Apakah yakin mau keluar?", "keluar aplikasi", JOptionPane.OK_OPTION);
        if(konfirmasi == JOptionPane.OK_OPTION)
        {
            dispose();
        }
    }//GEN-LAST:event_btnSelesaiActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PembelianTiket.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PembelianTiket.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PembelianTiket.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PembelianTiket.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PembelianTiket().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnHitung;
    private javax.swing.JButton btnPesan;
    private javax.swing.JButton btnPesanLagi;
    private javax.swing.JButton btnSelesai;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox<String> cbMaskapai;
    private javax.swing.JComboBox<String> cbTujuan;
    private javax.swing.JTextField formHargaTiket;
    private javax.swing.JTextField formJumlahTiket;
    private javax.swing.JTextField formNama;
    private javax.swing.JTextField formTotalHarga;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblHargaTiket;
    private javax.swing.JLabel lblJudul;
    private javax.swing.JLabel lblJumlahTiket;
    private javax.swing.JLabel lblMaskapai;
    private javax.swing.JLabel lblNama;
    private javax.swing.JLabel lblTipe;
    private javax.swing.JLabel lblTotalHarga;
    private javax.swing.JLabel lblTujuan;
    private javax.swing.JRadioButton rbBisnis;
    private javax.swing.JRadioButton rbEkonomi;
    private javax.swing.JRadioButton rbEksekutif;
    // End of variables declaration//GEN-END:variables
}
